## <center> Transforming Data(Feature engineering)</center>

- apply()
- map()
- assign()
- replace(old ,new)

In [202]:
import pandas as pd

In [203]:
# Feature engineering
df = pd.read_csv("raw_data.csv")
df2 = df.copy()


df2["tax"] = df2["Salary"].apply(lambda x : "20%" if x >= 50000 else "10%")


# suppose we wants to change Male = M, Female = F, Unknown + U

gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"}
df2["gender"] = df2["gender"].map(gender_map)

#Assign
df2.assign(new_income = df2["Salary"]  * 1.1)

#Replace
df2["country"] = df2["country"].replace("USA","US")
df2

   ID     Name  Age Department  Salary   country gender  tax
0   1    Alice   25         HR   55000     'USA'    NaN  20%
1   2      Bob   32         IT   72000     'USA'      F  20%
2   3  Charlie   28    Finance   48000     'UAE'      M  10%
3   4    David   45  Marketing   91000     'UAE'      U  20%
4   5      Eva   38         IT   65000     'USA'      F  20%
5   6    Frank   29    Finance   50000  'FRENCH'      M  20%
6   7    Grace   41         HR   82000  'RUSSIA'      F  20%
7   8   Hannah   26  Marketing   47000   'INDIA'      M  10%
8   9      Ian   35         IT   75000   'JAPAN'      M  20%
9  10    Julia   30    Finance   60000   'CHINA'      M  20%

In [204]:
df2

   ID     Name  Age Department  Salary   country gender  tax
0   1    Alice   25         HR   55000     'USA'    NaN  20%
1   2      Bob   32         IT   72000     'USA'      F  20%
2   3  Charlie   28    Finance   48000     'UAE'      M  10%
3   4    David   45  Marketing   91000     'UAE'      U  20%
4   5      Eva   38         IT   65000     'USA'      F  20%
5   6    Frank   29    Finance   50000  'FRENCH'      M  20%
6   7    Grace   41         HR   82000  'RUSSIA'      F  20%
7   8   Hannah   26  Marketing   47000   'INDIA'      M  10%
8   9      Ian   35         IT   75000   'JAPAN'      M  20%
9  10    Julia   30    Finance   60000   'CHINA'      M  20%

## OTHER 

---

- rename(columns={old:new})
- sort_values()
- sort_index()
- reset_index()
- rank()
- Reorder columns
---

In [ ]:
#Rename 
df2
# df2.columns = ["ID", "Name", "Age" , "country", "gender","Salary"]
df2.rename(columns={"Salary":"Income"})
df2.rename(index={1:"First"})



df2["Salary"].sort_values()
df2.sort_values("Salary")

sorted_df = df2.sort_values(["Salary", "Age"])
df2 = df2.fillna(50)

# df2.sort_valuess("Salary", ascending = False)

#df2.sort_value ("Income", "Age"])

sorted_df.sort_index()

sorted_df.reset_index()
sorted_df.reset_index(drop =True)

# Ranking
sorted_df["Ranking"] = sorted_df["Salary"].rank(ascending=False, method = "dense")  # when ever values are going to tie it's take it's average
sorted_df

   ID     Name  Age Department  Salary   country gender  tax  Ranking
7   8   Hannah   26  Marketing   47000   'INDIA'      M  10%     10.0
2   3  Charlie   28    Finance   48000     'UAE'      M  10%      9.0
5   6    Frank   29    Finance   50000  'FRENCH'      M  20%      8.0
0   1    Alice   25         HR   55000     'USA'    NaN  20%      7.0
9  10    Julia   30    Finance   60000   'CHINA'      M  20%      6.0
4   5      Eva   38         IT   65000     'USA'      F  20%      5.0
1   2      Bob   32         IT   72000     'USA'      F  20%      4.0
8   9      Ian   35         IT   75000   'JAPAN'      M  20%      3.0
6   7    Grace   41         HR   82000  'RUSSIA'      F  20%      2.0
3   4    David   45  Marketing   91000     'UAE'      U  20%      1.0